// The home-screen / PWA icon set.
//
// Two things were broken and are easy to break again, because nothing about
// either is visible on the site itself:
//
//   * `apple-touch-icon` pointed at assets/favicon.svg on every page. Safari
//     does not accept an SVG there — it ignores the tag and puts a screenshot
//     of the page on the home screen instead.
//   * manifest.json declared one SVG icon. Android's install flow looks for a
//     192 and a 512 PNG, and wants a `maskable` one so the launcher can crop
//     to its own shape without cutting through the artwork.
//
// The icons are generated by scripts/build-icons.mjs from the same geometry as
// assets/favicon.svg, and are NOT rebuilt by the content build — so this file
// is what notices if they go stale, go missing, or stop matching the sizes the
// manifest promises. A manifest that names a 512x512 and ships a 180 fails the
// install criteria silently, with no error anywhere.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readStable, allBoardPages } from "./helpers/generated.mjs";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const manifest = JSON.parse(readFileSync(join(ROOT, "manifest.json"), "utf8"));

/** Minimal PNG reader — IHDR dimensions plus a pixel accessor. */
function readPng(relPath) {
  const d = readFileSync(join(ROOT, relPath));
  assert.deepEqual([...d.subarray(0, 8)], [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], `${relPath} is not a PNG`);
  let i = 8, idat = [], width = 0, height = 0, depth = 0, colorType = 0;
  while (i < d.length) {
    const len = d.readUInt32BE(i);
    const type = d.subarray(i + 4, i + 8).toString("latin1");
    if (type === "IHDR") {
      width = d.readUInt32BE(i + 8);
      height = d.readUInt32BE(i + 12);
      depth = d[i + 16];
      colorType = d[i + 17];
    }
    if (type === "IDAT") idat.push(d.subarray(i + 8, i + 8 + len));
    i += 12 + len;
  }
  assert.equal(depth, 8, `${relPath} is not 8-bit`);
  assert.equal(colorType, 6, `${relPath} is not RGBA`);
  const raw = inflateSync(Buffer.concat(idat));
  const stride = width * 4 + 1;
  // Filter byte 0 (None) on every scanline is what build-icons.mjs writes; if
  // that ever changes this reader needs a real unfilter step, so assert it.
  for (let y = 0; y < height; y++) assert.equal(raw[y * stride], 0, `${relPath} scanline ${y} is filtered`);
  const px = (x, y) => {
    const o = y * stride + 1 + x * 4;
    return [raw[o], raw[o + 1], raw[o + 2], raw[o + 3]];
  };
  return { width, height, px };
}

test("every icon the manifest names actually exists", () => {
  assert.ok(manifest.icons.length >= 4, "the manifest lost icon entries");
  for (const icon of manifest.icons) {
    const rel = icon.src.replace(/^\//, "");
    assert.ok(existsSync(join(ROOT, rel)), `manifest names ${icon.src}, which is not in the repo`);
  }
});

test("each PNG's real dimensions match the size the manifest promises", () => {
  // The silent failure: a wrong `sizes` value makes the install prompt never
  // appear, with nothing logged anywhere to say why.
  for (const icon of manifest.icons.filter((i) => i.type === "image/png")) {
    const { width, height } = readPng(icon.src.replace(/^\//, ""));
    const [w, h] = icon.sizes.split("x").map(Number);
    assert.equal(width, w, `${icon.src} declares ${icon.sizes} but is ${width}px wide`);
    assert.equal(height, h, `${icon.src} declares ${icon.sizes} but is ${height}px tall`);
  }
});

test("the install-critical pair is present as PNG", () => {
  const png = manifest.icons.filter((i) => i.type === "image/png" && i.purpose === "any").map((i) => i.sizes);
  assert.ok(png.includes("192x192"), "no 192x192 PNG — Android's install flow looks for one");
  assert.ok(png.includes("512x512"), "no 512x512 PNG — Android's install flow looks for one");
});

test("the maskable icon survives any launcher crop", () => {
  // This is the entire reason a separate maskable variant exists: a launcher
  // may crop to a circle, a squircle, or a rounded square, and only the inner
  // circle of 40% radius is guaranteed to survive. So nothing but flat
  // background may appear outside it — otherwise a device somewhere slices
  // through the mark.
  const entry = manifest.icons.find((i) => i.purpose === "maskable");
  assert.ok(entry, "the manifest has no maskable icon");
  const { width, px } = readPng(entry.src.replace(/^\//, ""));
  const c = width / 2, r = 0.4 * width;
  const bg = px(0, 0);
  assert.equal(bg[3], 255, "a maskable icon must be fully opaque — the launcher supplies the shape");

  let strays = 0;
  for (let y = 0; y < width; y += 2) {
    for (let x = 0; x < width; x += 2) {
      if ((x - c) ** 2 + (y - c) ** 2 <= r * r) continue;
      const p = px(x, y);
      if (p[0] !== bg[0] || p[1] !== bg[1] || p[2] !== bg[2]) strays++;
    }
  }
  assert.equal(strays, 0, `${strays} sampled pixels of artwork fall outside the maskable safe zone and may be cropped away`);
});

test("the plain icon has transparent corners, so it is not a dark square", () => {
  const { width, px } = readPng("assets/icons/icon-512.png");
  assert.equal(px(0, 0)[3], 0, "the top-left corner is opaque — the rounded tile reads as a square");
  assert.equal(px(width - 1, width - 1)[3], 0, "the bottom-right corner is opaque");
  assert.equal(px(Math.floor(width / 2), Math.floor(width / 2))[3], 255, "the middle of the tile is transparent");
});

test("no page offers Safari an SVG apple-touch-icon", () => {
  const pages = [
    ["index.html"], ["control.html"], ["404.html"], ["about.html"], ["compare.html"],
    ["how-it-works.html"], ["privacy.html"], ["terms.html"], ["contact.html"],
    ["guides", "index.html"],
    ...allBoardPages().map(([parts]) => parts),
  ];
  for (const p of pages) {
    const html = readStable(...p);
    const tag = html.match(/<link rel="apple-touch-icon"[^>]*>/);
    assert.ok(tag, `${p.join("/")} has no apple-touch-icon`);
    assert.match(tag[0], /\.png"/, `${p.join("/")} offers Safari an ${tag[0].includes(".svg") ? "SVG" : "unknown"} apple-touch-icon, which it ignores`);
  }
});

test("every page a visitor could install from links the manifest", () => {
  // /about and /compare carried neither the manifest nor a touch icon, so
  // "Add to Home Screen" from those pages installed nothing.
  const pages = [
    ["index.html"], ["about.html"], ["compare.html"], ["how-it-works.html"],
    ["privacy.html"], ["terms.html"], ["contact.html"], ["guides", "index.html"],
    ...allBoardPages().map(([parts]) => parts),
  ];
  for (const p of pages) {
    assert.match(readStable(...p), /<link rel="manifest"/, `${p.join("/")} does not link the manifest`);
  }
});
