#!/usr/bin/env node
/**
 * The single command an agent (or Bruno) runs to know "what's the state of
 * outreach, and what's left." Reads/writes docs/outreach-ledger.json — the
 * only file in this project that tracks outreach PROGRESS (as opposed to
 * docs/submission-kit.json, which is just the static "what to say / where"
 * reference regenerated by scripts/generate-submission-kit.mjs).
 *
 * Why a separate ledger instead of one combined file: the kit is safe to
 * regenerate anytime (it has no memory); the ledger is NOT safe to
 * regenerate, because it's the only record of what's actually been done.
 * Keeping them apart means re-running the kit generator can never wipe out
 * real progress, and a future agent picking this up mid-stream never has to
 * guess what already happened — it reads the ledger.
 *
 * Commands:
 *   node scripts/outreach-status.mjs sync
 *     Merges docs/submission-kit.json's target list into the ledger:
 *     - new targets are added with a sensible default status
 *     - existing targets keep their current status/notes/last_run untouched
 *     - targets no longer in the kit are dropped (warns if they had progress)
 *     Safe to run after every scripts/generate-submission-kit.mjs run.
 *
 *   node scripts/outreach-status.mjs [status]   (default command)
 *     Prints a dashboard: counts by status and execution type, then a single
 *     consolidated list of everything that needs a human right now — this is
 *     the ONE place a human-in-the-loop checkpoint should ever be surfaced
 *     from, not scattered per-item as they're discovered. Also regenerates
 *     docs/submission-checklist.md as a human-readable render of the ledger.
 *
 *   node scripts/outreach-status.mjs set <id> <status> ["notes"]
 *     Updates one target's status (pending|in_progress|done|blocked|skipped)
 *     and optional notes/blocked_reason, stamps last_run. This is how an
 *     agent (or a future, more capable one) records that it actually
 *     attempted something, so the next run — by anyone — never duplicates
 *     work already done or retries a wall it already hit.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SITE_URL } from "./site-config.mjs";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const LEDGER_PATH = join(ROOT, "docs", "outreach-ledger.json");
const KIT_PATH = join(ROOT, "docs", "submission-kit.json");
const CHECKLIST_PATH = join(ROOT, "docs", "submission-checklist.md");

const DOMAIN_IS_PLACEHOLDER = SITE_URL.includes(".example");
const VALID_STATUSES = ["pending", "in_progress", "done", "blocked", "skipped"];
// Exact-match sentinel: only entries blocked for THIS specific reason get
// auto-unblocked by sync. Anything blocked for a different reason (a CAPTCHA
// wall, a missing account) keeps that reason and stays blocked — sync only
// ever clears the one condition it itself set.
const DOMAIN_BLOCKED_REASON = "Waiting on real domain purchase + deploy — see docs/seo-outreach-plan.md.";

async function readJsonSafe(path, fallback) {
  try { return JSON.parse(await readFile(path, "utf-8")); }
  catch { return fallback; }
}

async function cmdSync() {
  const kit = await readJsonSafe(KIT_PATH, null);
  if (!kit) {
    console.error("docs/submission-kit.json not found — run `node scripts/generate-submission-kit.mjs` first.");
    process.exit(1);
  }
  const ledger = await readJsonSafe(LEDGER_PATH, { targets: {} });
  const kitIds = new Set(kit.targets.map(t => t.id));

  // Drop entries whose target no longer exists in the kit; warn if they had real progress.
  for (const id of Object.keys(ledger.targets)) {
    if (!kitIds.has(id)) {
      const entry = ledger.targets[id];
      if (entry.status && entry.status !== "pending") {
        console.warn(`Warning: dropping ledger entry "${id}" (status was "${entry.status}") — no longer in submission-kit.json targets.`);
      }
      delete ledger.targets[id];
    }
  }

  let added = 0, unblocked = 0;
  for (const t of kit.targets) {
    if (ledger.targets[t.id]) {
      // Existing entry: re-evaluate ONLY if it's still sitting in the exact
      // auto-generated "waiting on domain" state sync itself set — this is
      // what actually delivers the "flips to pending automatically" promise
      // in docs/seo-outreach-plan.md, which otherwise only applied to
      // brand-new targets, not the ones already in the ledger from before
      // the domain was real.
      const entry = ledger.targets[t.id];
      if (entry.status === "blocked" && entry.blocked_reason === DOMAIN_BLOCKED_REASON && !DOMAIN_IS_PLACEHOLDER) {
        entry.status = "pending";
        entry.blocked_reason = null;
        unblocked++;
      }
      continue;
    }
    const blocked = t.gated_on_domain && DOMAIN_IS_PLACEHOLDER;
    ledger.targets[t.id] = {
      name: t.name,
      execution: t.execution,
      status: blocked ? "blocked" : "pending",
      blocked_reason: blocked ? DOMAIN_BLOCKED_REASON : null,
      last_run: null,
      notes: "",
    };
    added++;
  }

  ledger.last_synced = new Date().toISOString();
  await writeFile(LEDGER_PATH, JSON.stringify(ledger, null, 2), "utf-8");
  console.log(`Synced. ${added} new target(s) added, ${unblocked} unblocked now that the domain is real, ${Object.keys(ledger.targets).length} total tracked.`);
  if (DOMAIN_IS_PLACEHOLDER) {
    console.log("Note: SITE_URL is still a .example placeholder — every domain-gated target was added as \"blocked\".");
  }
}

async function cmdSet(id, status, notes) {
  if (!VALID_STATUSES.includes(status)) {
    console.error(`Invalid status "${status}". Must be one of: ${VALID_STATUSES.join(", ")}`);
    process.exit(1);
  }
  const ledger = await readJsonSafe(LEDGER_PATH, null);
  if (!ledger || !ledger.targets[id]) {
    console.error(`Unknown target id "${id}". Run "node scripts/outreach-status.mjs sync" first, or check docs/outreach-ledger.json for valid ids.`);
    process.exit(1);
  }
  ledger.targets[id].status = status;
  ledger.targets[id].last_run = new Date().toISOString();
  if (notes) ledger.targets[id].notes = notes;
  if (status === "blocked" && notes) ledger.targets[id].blocked_reason = notes;
  if (status !== "blocked") ledger.targets[id].blocked_reason = null;
  await writeFile(LEDGER_PATH, JSON.stringify(ledger, null, 2), "utf-8");
  console.log(`${id} -> ${status}${notes ? ` ("${notes}")` : ""}`);
}

function checklistMd(kit, ledger) {
  const rows = kit.targets.map(t => {
    const l = ledger.targets[t.id] || {};
    const statusLabel = {
      done: "done", pending: "not started", in_progress: "in progress",
      blocked: `blocked — ${l.blocked_reason || "see notes"}`, skipped: "skipped",
    }[l.status || "pending"];
    return `| ${t.name} | \`${t.execution}\` | ${t.notes} | ${statusLabel} |`;
  });
  return `# Submission checklist (generated — do not hand-edit)

This file is a rendering of \`docs/outreach-ledger.json\` (actual state) plus
\`docs/submission-kit.json\` (copy + target definitions). To change status,
run \`node scripts/outreach-status.mjs set <id> <status> "notes"\` — editing
this file directly will be overwritten on the next run.

## Copy to paste (source of truth: docs/submission-kit.json)

**Name:** ${kit.copy.name}
**Tagline:** ${kit.copy.tagline}
**One-liner:** ${kit.copy.one_liner}
**Short description:** ${kit.copy.short_description}
**Tags:** ${kit.copy.category_tags.join(", ")}
**Pricing:** ${kit.copy.pricing}

<details><summary>Long description (for sites that want more)</summary>

${kit.copy.long_description}

</details>

## Targets

| Target | Execution | Notes | Status |
|---|---|---|---|
${rows.join("\n")}
`;
}

async function cmdStatus() {
  const kit = await readJsonSafe(KIT_PATH, null);
  const ledger = await readJsonSafe(LEDGER_PATH, null);
  if (!kit || !ledger) {
    console.error("Missing docs/submission-kit.json or docs/outreach-ledger.json — run:\n  node scripts/generate-submission-kit.mjs\n  node scripts/outreach-status.mjs sync");
    process.exit(1);
  }

  const entries = Object.entries(ledger.targets);
  const byStatus = {};
  for (const [, e] of entries) byStatus[e.status] = (byStatus[e.status] || 0) + 1;

  console.log(`Outreach status — ${entries.length} targets tracked (last synced ${ledger.last_synced || "never"})\n`);
  for (const s of VALID_STATUSES) if (byStatus[s]) console.log(`  ${s.padEnd(12)} ${byStatus[s]}`);

  const humanNeeded = entries.filter(([, e]) => e.status === "pending" || e.status === "blocked")
    .filter(([id]) => kit.targets.find(t => t.id === id)?.execution === "human-required");
  const agentActionable = entries.filter(([, e]) => e.status === "pending")
    .filter(([id]) => ["script", "agent-browser"].includes(kit.targets.find(t => t.id === id)?.execution));

  if (agentActionable.length) {
    console.log(`\n${agentActionable.length} target(s) ready for an agent to attempt directly:`);
    for (const [id, e] of agentActionable) console.log(`  - ${e.name} (${id})`);
  }
  if (humanNeeded.length) {
    console.log(`\n${humanNeeded.length} target(s) need Bruno specifically — consolidated here, not raised one at a time:`);
    for (const [id, e] of humanNeeded) {
      console.log(`  - ${e.name}${e.status === "blocked" ? ` — BLOCKED: ${e.blocked_reason}` : ""}`);
    }
  }

  await writeFile(CHECKLIST_PATH, checklistMd(kit, ledger), "utf-8");
  console.log("\nWrote docs/submission-checklist.md");
}

const [, , cmd, a, b] = process.argv;
if (cmd === "sync") await cmdSync();
else if (cmd === "set") await cmdSet(a, b, process.argv[5]);
else await cmdStatus();
